[package]
name = "norg_pandoc_rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["lib"]

[dependencies]
clap = { version = "4.3.12", features = ["derive"] }
rusty_pool = "0.7.0"
walkdir = "2.3.3"
norg_pandoc_ast = { path = "lib" }
