name: DOC

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  scan_changes:
    runs-on: ubuntu-latest
    outputs: 
      readme: ${{ steps.filter.outputs.readme }}
      lib_readme: ${{ steps.filter.outputs.lib_readme }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            readme: README.norg
            lib_readme: lib/README.norg
  docs:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    needs:
      - scan_changes
    if: ${{ needs.scan_changes.outputs.readme == 'true' || needs.scan_changes.outputs.lib_readme == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y pandoc
      - uses: Swatinem/rust-cache@v2
      - name: Generate documentation
        run: cargo run -- -t md ./ -- --to=gfm
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): update README.md"
          commit_user_name: "github_actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
