name: DOC

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  scan_changes:
    runs-on: ubuntu-latest
    outputs: 
      readme: ${{ steps.filter.outputs.readme }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            readme: README.norg
  docs:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    needs:
      - scan_changes
    if: ${{ needs.scan_changes.outputs.readme == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            readme:
              - 'README.norg'
      - name: Generate pandoc ast
        run: cargo run --release -- README.norg >> t.json
      - name: Generate markdown file from ast
        uses: docker://pandoc/core:3
        with:
          args: >-
            --from=json
            --to=gfm
            --output=README.md
            t.json
      - name: Remove AST file
        run: rm t.json
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): update README.md"
          commit_user_name: "github_actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
